name = "dtiktok-website"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
watch_dir = "src"

[build.upload]
format = "service-worker"

[site]
bucket = ".next"
entry-point = "_worker.js"

[env.production]
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "/*", zone_name = "dtiktok-website.pages.dev" }
]

[pages]
pages_build_output_dir = ".next"
